# Generated by Django 6.1.1 on 2026-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed', models.DateTimeField(default=False)),
                ('parsed_error', models.TextField(blank=True, default=False)),
            ],
        ),
    ]
